### ISSUE TITLE
Bad rendering of rotated cursors in Firefox

### ISSUE THREAD

**Issue by martinpare** [jwarby/jquery-awesome-cursor#10]
When cursor is rotated, some unwanted "frills" appear. Have a look at the Green Pencil With Brown Outline example on home page or project, in Firefox.

Otherwise, this plugin is great!

Thanks in advance for follow-up.

**Comment by jwarby** [comment]
Hi @martinpare, thanks for raising this.  Able to reproduce it, though I found the problem is even worse with the Blue Rotated Hand example.  Could you confirm this is also the case for yourself?

I'm currently away on holiday at the moment, so won't be able to look further at this issue until at least next week sorry.

**Comment by martinpare** [comment]
Hi, @jwarby,

Thanks for such quick answer. It is really appreciated. Also, I confirm that the Blue Rotated Hand example is worse! But everything is fine in Opera, Safari and Chrome except, of course IE).

Thanks again.
